### PR TITLE
Make universal wheels.

### PR DESCRIPTION
**Pull request by ionelmc**
See https://packaging.python.org/en/latest/distributing.html#universal-wheels

### CODE REVIEW

**Comment by mgedmin** [comment]
The problem with this approach is that install_requires and tests_require in setup.py differ on Python 2.6 and on other Python versions.

**Comment by ionelmc** [comment]
You mean something like this https://wheel.readthedocs.org/en/latest/#defining-conditional-dependencies? :grin: 

Also, `tests_require` is irrelevant in the scope of wheels (it's not something pertinent to installs).

**Comment by mgedmin** [comment]
Yes, that's the correct approach for the future.  I'm not sure the version of setuptools (or was it pip?) that supports this feature is sufficiently widely deployed yet.

There's another approach, specifying the wheel dependencies in setup.cfg, that also allows conditions on the Python version.  It ought to work with older setuptools/pip versions.  I don't remember the syntax, though, and I wouldn't enjoy the duplication of dependency information.

The current method of specifying conditional deps has its share of problems, one of which is a race condition in detox that breaks rebuilds sometimes.  I'd be happy to see it gone.  I'm just not sure how or when to do that.

Dropping Python 2.6 support is also an option.  (The main problem is that there are many options and I can't decide on one.)

**Comment by mgedmin** [comment]
> I'm not sure the version of setuptools (or was it pip?) that supports this feature is sufficiently widely deployed yet.

The version of setuptools that added support for PEP-426 environment markers was 0.7.

That's *old*!  I think we can safely assume it has been "sufficiently deployed yet".

**Pull request merged**
