### PR TITLE
Add trove classifiers for general Python 2/3 support

### PR DESCRIPTION
**Pull request by jdufresne**
For a full list of classifiers, see:

https://pypi.org/pypi?%3Aaction=list_classifiers

### CODE REVIEW

**Comment by mgedmin** [comment]
Could you provide a reason for having this?  They seem redundant, given the more specific 2.x and 3.y classifiers I already have.  I've always considered these to mean "we support some versions of Python X, but we can't be bothered to say which ones".

**Comment by jdufresne** [comment]
These trove classifiers signal to potential library users that it has Python 2/3 support in some capacity. I find including them is more accurate. These classifiers are also used by scripts.

**Comment by jdufresne** [comment]
FWIW, high profile and prominent packages include these.

**Comment by mgedmin** [comment]
> These trove classifiers signal to potential library users that it has Python 2/3 support in some capacity. I find including them is more accurate. These classifiers are also used by scripts.

I was hoping for some specifics?  Or a link to some recommendation in the Python Packaging manual/a blog post/anything?

Are there scripts that do not understand 'Programming Language :: Python :: 3.7' implies 'Programming Language :: Python :: 3'?

I'm not opposed to adding these, but if there's a good reason to add them, then I'd like to add them to all the packages I maintain.  And it's a bit of work (I maintain over a dozen).

**Comment by jdufresne** [comment]
Sorry, I don't have a link to an authoritative source. This is just habits I picked up over time from working with other packages. Cheers.

**Comment by mgedmin** [comment]
Thanks anyway!

**Pull request merged**
